[tool.uv.workspace]
members = ["engine", "api"]

[tool.black]
line-length = 88
target-version = ["py311"]

[tool.ruff]
line-length = 88
target-version = "py311"
extend-select = ["I"]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q"
testpaths = ["engine/tests", "api/tests"]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest",
    "hypothesis",
    "ruff",
    "black",
    "pre-commit",
]
